### ISSUE TITLE
Running polyglot as module

### ISSUE THREAD

**Issue by poyea** [lainq/polyglot#14]
**Is your feature request related to a problem? Please describe.**
This is a feature request as in some cases directly printing in the console is more useful. I wonder if there's a way to achieve this on top of the current functionality.

**Describe the solution you'd like**
In the console,
```bash
$ python -m polyglot .
+-------------------------+-------+
|         Language        | Files |
+-------------------------+-------+
|       Ignore List       |  0.07 |
|           YAML          |  0.07 |
|       Unknown file      | 53.35 |
| GCC Machine Description |  0.2  |
|           Text          |  2.63 |
|          Python         |  42.9 |
|         HAProxy         |  0.13 |
|     reStructuredText    |  0.2  |
|           JSON          |  0.2  |
|           XML           |  0.07 |
|        Batchfile        |  0.13 |
|        PowerShell       |  0.07 |
+-------------------------+-------+
```

**Comment by poyea** [comment]
Examples:
* `python -m timeit -h`
* `python -m pip install something`
* `python -m pytest [...]`
etc.

**Comment by pranavbaburaj** [comment]
Thank you for your suggestion. We have built a simple [cli](https://github.com/pranavbaburaj/polyglot/blob/main/cli.py) right now. I guess we need to move it from `./cli.py` to `./polyglot/__main__.py`. 🤔

**Comment by pranavbaburaj** [comment]
I have fixed the issue. Thank you. I am closing this issue 🙂
